/**
 * NEO Dashboard - Auto-generated Data
 * Last updated: 2026-10-09T07:58:32.995046
 *
 * Sources: NASA NEOWS, MPC NEO Confirmation Page, NASA SBDB
 * DO NOT EDIT - regenerated by generate_static_api.py
 */

function generateDashboardData() {
    return {
    "meta": {
        "lastUpdate": "2026-10-09T07:58:32.995046",
        "sources": [
            "NASA NEOWS",
            "MPC NEO Confirmation Page",
            "NASA SBDB"
        ],
        "version": "2.0"
    },
    "catalog": {
        "totalNEOs": 62621,
        "phaCount": 2550,
        "newThisYear": 2038,
        "newThisMonth": 114,
        "orbitClasses": {
            "Amor": 14894,
            "Apollo": 24266,
            "Aten": 3475,
            "IEO": 38
        }
    },
    "approaches": [],
    "candidates": [
        {
            "id": "C46NWU1",
            "designation": "C46NWU1",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "31.9",
            "obs": "6",
            "arc": "0.03",
            "status": "pending"
        },
        {
            "id": "C46NVG1",
            "designation": "C46NVG1",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "30.9",
            "obs": "9",
            "arc": "0.07",
            "status": "pending"
        },
        {
            "id": "CEWL7R2",
            "designation": "CEWL7R2",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "29.1",
            "obs": "8",
            "arc": "0.06",
            "status": "pending"
        },
        {
            "id": "CEWH582",
            "designation": "CEWH582",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "098",
            "mag": "28.9",
            "obs": "10",
            "arc": "0.09",
            "status": "pending"
        },
        {
            "id": "CEWGUW2",
            "designation": "CEWGUW2",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "29.2",
            "obs": "10",
            "arc": "0.07",
            "status": "pending"
        },
        {
            "id": "CEWGHC2",
            "designation": "CEWGHC2",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "086",
            "mag": "29.2",
            "obs": "10",
            "arc": "0.10",
            "status": "pending"
        },
        {
            "id": "CARD7TZ",
            "designation": "CARD7TZ",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "27.2",
            "obs": "4",
            "arc": "0.02",
            "status": "pending"
        },
        {
            "id": "CARD7VZ",
            "designation": "CARD7VZ",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "28.3",
            "obs": "4",
            "arc": "0.02",
            "status": "pending"
        },
        {
            "id": "XL1008A",
            "designation": "XL1008A",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "30.0",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "c1gkj45",
            "designation": "c1gkj45",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "28.0",
            "obs": "11",
            "arc": "2.96",
            "status": "pending"
        },
        {
            "id": "TKO0001",
            "designation": "TKO0001",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "086",
            "mag": "30.0",
            "obs": "20",
            "arc": "0.51",
            "status": "pending"
        },
        {
            "id": "CEVYPN2",
            "designation": "CEVYPN2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "086",
            "mag": "27.9",
            "obs": "8",
            "arc": "0.89",
            "status": "pending"
        },
        {
            "id": "ZTF10Gh",
            "designation": "ZTF10Gh",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "29.7",
            "obs": "8",
            "arc": "0.02",
            "status": "pending"
        },
        {
            "id": "A11HOcS",
            "designation": "A11HOcS",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "091",
            "mag": "30.6",
            "obs": "18",
            "arc": "0.59",
            "status": "pending"
        },
        {
            "id": "C1GV6U5",
            "designation": "C1GV6U5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "097",
            "mag": "28.3",
            "obs": "11",
            "arc": "0.79",
            "status": "pending"
        },
        {
            "id": "C1GUXM5",
            "designation": "C1GUXM5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "098",
            "mag": "27.8",
            "obs": "10",
            "arc": "0.81",
            "status": "pending"
        },
        {
            "id": "CEWAAC2",
            "designation": "CEWAAC2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "098",
            "mag": "28.6",
            "obs": "12",
            "arc": "0.89",
            "status": "pending"
        },
        {
            "id": "CEW76J2",
            "designation": "CEW76J2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "092",
            "mag": "28.2",
            "obs": "10",
            "arc": "0.93",
            "status": "pending"
        },
        {
            "id": "C1GTXK5",
            "designation": "C1GTXK5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "085",
            "mag": "27.1",
            "obs": "8",
            "arc": "0.07",
            "status": "pending"
        },
        {
            "id": "CEW8VV2",
            "designation": "CEW8VV2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "095",
            "mag": "28.9",
            "obs": "13",
            "arc": "0.93",
            "status": "pending"
        },
        {
            "id": "C1GTPE5",
            "designation": "C1GTPE5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "098",
            "mag": "27.8",
            "obs": "10",
            "arc": "0.80",
            "status": "pending"
        },
        {
            "id": "C1GTPF5",
            "designation": "C1GTPF5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "27.0",
            "obs": "7",
            "arc": "0.06",
            "status": "pending"
        },
        {
            "id": "CEW8F82",
            "designation": "CEW8F82",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "086",
            "mag": "28.6",
            "obs": "16",
            "arc": "2.05",
            "status": "pending"
        },
        {
            "id": "C1GR325",
            "designation": "C1GR325",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "089",
            "mag": "27.6",
            "obs": "6",
            "arc": "0.06",
            "status": "pending"
        },
        {
            "id": "C1GR0W5",
            "designation": "C1GR0W5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "097",
            "mag": "28.5",
            "obs": "13",
            "arc": "0.91",
            "status": "pending"
        },
        {
            "id": "CEW2VG2",
            "designation": "CEW2VG2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "088",
            "mag": "28.8",
            "obs": "19",
            "arc": "0.92",
            "status": "pending"
        },
        {
            "id": "6K72D21",
            "designation": "6K72D21",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "086",
            "mag": "29.0",
            "obs": "17",
            "arc": "1.00",
            "status": "pending"
        },
        {
            "id": "C1GQWZ5",
            "designation": "C1GQWZ5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "044",
            "mag": "28.0",
            "obs": "9",
            "arc": "0.83",
            "status": "pending"
        },
        {
            "id": "CEVYPP2",
            "designation": "CEVYPP2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "093",
            "mag": "28.0",
            "obs": "21",
            "arc": "0.90",
            "status": "pending"
        },
        {
            "id": "C1GQQN5",
            "designation": "C1GQQN5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "28.1",
            "obs": "13",
            "arc": "4.97",
            "status": "pending"
        },
        {
            "id": "C46NDW1",
            "designation": "C46NDW1",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "098",
            "mag": "30.2",
            "obs": "10",
            "arc": "0.23",
            "status": "pending"
        },
        {
            "id": "orA5873",
            "designation": "orA5873",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "29.8",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "CANPMAZ",
            "designation": "CANPMAZ",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "27.6",
            "obs": "4",
            "arc": "0.02",
            "status": "pending"
        },
        {
            "id": "CEVT4K2",
            "designation": "CEVT4K2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "054",
            "mag": "28.7",
            "obs": "10",
            "arc": "0.93",
            "status": "pending"
        },
        {
            "id": "N033125",
            "designation": "N033125",
            "name": "",
            "first_seen": "2026-10-04",
            "observer": "097",
            "mag": "28.5",
            "obs": "4",
            "arc": "0.08",
            "status": "pending"
        },
        {
            "id": "N117108",
            "designation": "N117108",
            "name": "",
            "first_seen": "2026-10-02",
            "observer": "100",
            "mag": "",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "N015193",
            "designation": "N015193",
            "name": "",
            "first_seen": "2026-10-01",
            "observer": "100",
            "mag": "28.7",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "N015143",
            "designation": "N015143",
            "name": "",
            "first_seen": "2026-10-05",
            "observer": "100",
            "mag": "25.2",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "N051198",
            "designation": "N051198",
            "name": "",
            "first_seen": "2026-10-05",
            "observer": "085",
            "mag": "28.9",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "N125213",
            "designation": "N125213",
            "name": "",
            "first_seen": "2026-10-05",
            "observer": "092",
            "mag": "",
            "obs": "4",
            "arc": "0.08",
            "status": "pending"
        },
        {
            "id": "N070166",
            "designation": "N070166",
            "name": "",
            "first_seen": "2026-10-05",
            "observer": "100",
            "mag": "28.3",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "ZTF10Gf",
            "designation": "ZTF10Gf",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "098",
            "mag": "27.3",
            "obs": "8",
            "arc": "1.09",
            "status": "pending"
        },
        {
            "id": "CEVRWL2",
            "designation": "CEVRWL2",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "28.3",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "CEVQWE2",
            "designation": "CEVQWE2",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "29.0",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "CEVRR22",
            "designation": "CEVRR22",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "095",
            "mag": "29.7",
            "obs": "9",
            "arc": "0.92",
            "status": "pending"
        },
        {
            "id": "C1GN5U5",
            "designation": "C1GN5U5",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "098",
            "mag": "27.7",
            "obs": "11",
            "arc": "0.86",
            "status": "pending"
        },
        {
            "id": "C1GM215",
            "designation": "C1GM215",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "27.9",
            "obs": "15",
            "arc": "1.04",
            "status": "pending"
        },
        {
            "id": "C1GLQL5",
            "designation": "C1GLQL5",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "27.7",
            "obs": "10",
            "arc": "0.80",
            "status": "pending"
        },
        {
            "id": "C1GLFL5",
            "designation": "C1GLFL5",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "073",
            "mag": "28.5",
            "obs": "10",
            "arc": "0.81",
            "status": "pending"
        },
        {
            "id": "6K61321",
            "designation": "6K61321",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "083",
            "mag": "29.8",
            "obs": "39",
            "arc": "1.66",
            "status": "pending"
        }
    ],
    "tracker": {
        "totalCandidates": 126,
        "statusCounts": {
            "pending": 126
        },
        "topCandidates": [
            {
                "designation": "C46NWU1",
                "status": "pending"
            },
            {
                "designation": "C46NVG1",
                "status": "pending"
            },
            {
                "designation": "CEWL7R2",
                "status": "pending"
            },
            {
                "designation": "CEWH582",
                "status": "pending"
            },
            {
                "designation": "CEWGUW2",
                "status": "pending"
            },
            {
                "designation": "CEWGHC2",
                "status": "pending"
            },
            {
                "designation": "CARD7TZ",
                "status": "pending"
            },
            {
                "designation": "CARD7VZ",
                "status": "pending"
            },
            {
                "designation": "XL1008A",
                "status": "pending"
            },
            {
                "designation": "c1gkj45",
                "status": "pending"
            }
        ]
    },
    "stats": {
        "earlyDiscoveries": 77,
        "highConfidenceCandidates": 77,
        "avgLeadTimeDays": 0.0,
        "discoveryByYear": {
            "labels": [
                "2017",
                "2018",
                "2019",
                "2020",
                "2021",
                "2022",
                "2023",
                "2024",
                "2025",
                "2026"
            ],
            "data": [
                2002,
                1741,
                2305,
                2708,
                2877,
                2999,
                2784,
                3005,
                3157,
                2038
            ]
        }
    },
    "earlyDiscoveries": []
};
}
