/**
 * NEO Dashboard - Auto-generated Data
 * Last updated: 2026-10-09T08:01:40.804169
 *
 * Sources: NASA NEOWS, MPC NEO Confirmation Page, NASA SBDB
 * DO NOT EDIT - regenerated by generate_static_api.py
 */

function generateDashboardData() {
    return {
    "meta": {
        "lastUpdate": "2026-10-09T08:01:40.804169",
        "sources": [
            "NASA NEOWS",
            "MPC NEO Confirmation Page",
            "NASA SBDB"
        ],
        "version": "2.0"
    },
    "catalog": {
        "totalNEOs": 62621,
        "phaCount": 2550,
        "newThisYear": 2038,
        "newThisMonth": 114,
        "orbitClasses": {
            "Amor": 14894,
            "Apollo": 24266,
            "Aten": 3475,
            "IEO": 38
        }
    },
    "approaches": [
        {
            "name": "2019 SD8",
            "desig": "",
            "date": "2026-10-10",
            "distLD": 17.87,
            "vel": 9.5,
            "pha": false
        },
        {
            "name": "2000 SZ162",
            "desig": "",
            "date": "2026-10-16",
            "distLD": 19.02,
            "vel": 5.7,
            "pha": false
        },
        {
            "name": "2020 QG3",
            "desig": "",
            "date": "2026-10-16",
            "distLD": 20.57,
            "vel": 10.1,
            "pha": true
        },
        {
            "name": "679786 (2020 QG3",
            "desig": "",
            "date": "2026-10-16",
            "distLD": 20.57,
            "vel": 10.1,
            "pha": true
        },
        {
            "name": "2018 EH4",
            "desig": "",
            "date": "2026-10-14",
            "distLD": 21.03,
            "vel": 13.2,
            "pha": true
        },
        {
            "name": "678976 (2018 EH4",
            "desig": "",
            "date": "2026-10-14",
            "distLD": 21.03,
            "vel": 13.2,
            "pha": true
        },
        {
            "name": "2009 TK8",
            "desig": "",
            "date": "2026-10-15",
            "distLD": 30.41,
            "vel": 14.9,
            "pha": false
        },
        {
            "name": "2012 WH1",
            "desig": "",
            "date": "2026-10-13",
            "distLD": 38.29,
            "vel": 7.0,
            "pha": false
        },
        {
            "name": "2019 GE1",
            "desig": "",
            "date": "2026-10-09",
            "distLD": 42.73,
            "vel": 3.6,
            "pha": false
        },
        {
            "name": "2013 JR22",
            "desig": "",
            "date": "2026-10-15",
            "distLD": 45.64,
            "vel": 21.0,
            "pha": false
        },
        {
            "name": "339714 (2005 ST1",
            "desig": "",
            "date": "2026-10-13",
            "distLD": 50.74,
            "vel": 14.3,
            "pha": false
        },
        {
            "name": "2020 DT2",
            "desig": "",
            "date": "2026-10-10",
            "distLD": 50.93,
            "vel": 16.3,
            "pha": false
        },
        {
            "name": "2017 HE49",
            "desig": "",
            "date": "2026-10-11",
            "distLD": 53.1,
            "vel": 7.0,
            "pha": false
        },
        {
            "name": "2020 BN10",
            "desig": "",
            "date": "2026-10-10",
            "distLD": 55.77,
            "vel": 18.3,
            "pha": true
        },
        {
            "name": "2010 DO",
            "desig": "",
            "date": "2026-10-13",
            "distLD": 57.5,
            "vel": 25.3,
            "pha": true
        },
        {
            "name": "2015 TG24",
            "desig": "",
            "date": "2026-10-13",
            "distLD": 70.33,
            "vel": 16.0,
            "pha": false
        },
        {
            "name": "164207 Cardea (2004 GU9",
            "desig": "",
            "date": "2026-10-12",
            "distLD": 74.04,
            "vel": 7.3,
            "pha": true
        },
        {
            "name": "2016 UZ41",
            "desig": "",
            "date": "2026-10-14",
            "distLD": 74.35,
            "vel": 15.3,
            "pha": false
        },
        {
            "name": "2017 RO17",
            "desig": "",
            "date": "2026-10-13",
            "distLD": 75.06,
            "vel": 8.4,
            "pha": false
        },
        {
            "name": "2016 UW35",
            "desig": "",
            "date": "2026-10-09",
            "distLD": 81.12,
            "vel": 5.0,
            "pha": false
        },
        {
            "name": "2013 RX80",
            "desig": "",
            "date": "2026-10-10",
            "distLD": 90.11,
            "vel": 25.8,
            "pha": false
        },
        {
            "name": "2019 SB1",
            "desig": "",
            "date": "2026-10-14",
            "distLD": 93.8,
            "vel": 22.5,
            "pha": false
        },
        {
            "name": "2011 UH20",
            "desig": "",
            "date": "2026-10-13",
            "distLD": 103.3,
            "vel": 24.3,
            "pha": true
        },
        {
            "name": "2017 SV14",
            "desig": "",
            "date": "2026-10-10",
            "distLD": 106.72,
            "vel": 10.1,
            "pha": false
        },
        {
            "name": "2003 QF70",
            "desig": "",
            "date": "2026-10-09",
            "distLD": 116.76,
            "vel": 6.4,
            "pha": false
        },
        {
            "name": "2015 KT121",
            "desig": "",
            "date": "2026-10-09",
            "distLD": 116.76,
            "vel": 10.8,
            "pha": false
        },
        {
            "name": "2016 UW80",
            "desig": "",
            "date": "2026-10-10",
            "distLD": 122.08,
            "vel": 7.7,
            "pha": false
        },
        {
            "name": "2015 XK55",
            "desig": "",
            "date": "2026-10-12",
            "distLD": 129.13,
            "vel": 15.4,
            "pha": false
        },
        {
            "name": "2018 VJ1",
            "desig": "",
            "date": "2026-10-09",
            "distLD": 136.35,
            "vel": 12.2,
            "pha": false
        },
        {
            "name": "2017 TM6",
            "desig": "",
            "date": "2026-10-15",
            "distLD": 146.42,
            "vel": 15.6,
            "pha": false
        },
        {
            "name": "2015 XN128",
            "desig": "",
            "date": "2026-10-16",
            "distLD": 148.47,
            "vel": 1.6,
            "pha": false
        },
        {
            "name": "2001 UP",
            "desig": "",
            "date": "2026-10-09",
            "distLD": 156.26,
            "vel": 20.8,
            "pha": false
        },
        {
            "name": "2009 SB170",
            "desig": "",
            "date": "2026-10-11",
            "distLD": 158.02,
            "vel": 40.5,
            "pha": false
        },
        {
            "name": "2011 PU1",
            "desig": "",
            "date": "2026-10-11",
            "distLD": 161.2,
            "vel": 6.2,
            "pha": false
        },
        {
            "name": "2015 HH10",
            "desig": "",
            "date": "2026-10-16",
            "distLD": 162.03,
            "vel": 20.9,
            "pha": false
        },
        {
            "name": "2021 JE4",
            "desig": "",
            "date": "2026-10-11",
            "distLD": 167.01,
            "vel": 16.7,
            "pha": false
        },
        {
            "name": "2015 TW237",
            "desig": "",
            "date": "2026-10-11",
            "distLD": 167.64,
            "vel": 5.0,
            "pha": false
        },
        {
            "name": "2017 VB13",
            "desig": "",
            "date": "2026-10-11",
            "distLD": 172.99,
            "vel": 15.4,
            "pha": false
        },
        {
            "name": "2016 TG56",
            "desig": "",
            "date": "2026-10-13",
            "distLD": 174.77,
            "vel": 15.4,
            "pha": false
        },
        {
            "name": "2015 TM143",
            "desig": "",
            "date": "2026-10-11",
            "distLD": 183.94,
            "vel": 21.9,
            "pha": false
        },
        {
            "name": "2019 EO2",
            "desig": "",
            "date": "2026-10-09",
            "distLD": 185.94,
            "vel": 19.9,
            "pha": false
        }
    ],
    "candidates": [
        {
            "id": "C46NXG1",
            "designation": "C46NXG1",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "30.2",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "C46NWU1",
            "designation": "C46NWU1",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "31.9",
            "obs": "6",
            "arc": "0.03",
            "status": "pending"
        },
        {
            "id": "C46NVG1",
            "designation": "C46NVG1",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "30.9",
            "obs": "9",
            "arc": "0.07",
            "status": "pending"
        },
        {
            "id": "CEWL7R2",
            "designation": "CEWL7R2",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "29.1",
            "obs": "8",
            "arc": "0.06",
            "status": "pending"
        },
        {
            "id": "CEWH582",
            "designation": "CEWH582",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "098",
            "mag": "28.9",
            "obs": "10",
            "arc": "0.09",
            "status": "pending"
        },
        {
            "id": "CEWGUW2",
            "designation": "CEWGUW2",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "100",
            "mag": "29.2",
            "obs": "10",
            "arc": "0.07",
            "status": "pending"
        },
        {
            "id": "CEWGHC2",
            "designation": "CEWGHC2",
            "name": "",
            "first_seen": "2026-10-09",
            "observer": "086",
            "mag": "29.2",
            "obs": "10",
            "arc": "0.10",
            "status": "pending"
        },
        {
            "id": "CARD7TZ",
            "designation": "CARD7TZ",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "27.1",
            "obs": "4",
            "arc": "0.02",
            "status": "pending"
        },
        {
            "id": "CARD7VZ",
            "designation": "CARD7VZ",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "28.3",
            "obs": "4",
            "arc": "0.02",
            "status": "pending"
        },
        {
            "id": "XL1008A",
            "designation": "XL1008A",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "30.0",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "c1gkj45",
            "designation": "c1gkj45",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "28.0",
            "obs": "11",
            "arc": "2.96",
            "status": "pending"
        },
        {
            "id": "TKO0001",
            "designation": "TKO0001",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "086",
            "mag": "30.0",
            "obs": "20",
            "arc": "0.51",
            "status": "pending"
        },
        {
            "id": "CEVYPN2",
            "designation": "CEVYPN2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "086",
            "mag": "27.9",
            "obs": "8",
            "arc": "0.89",
            "status": "pending"
        },
        {
            "id": "ZTF10Gh",
            "designation": "ZTF10Gh",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "29.7",
            "obs": "8",
            "arc": "0.02",
            "status": "pending"
        },
        {
            "id": "A11HOcS",
            "designation": "A11HOcS",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "091",
            "mag": "30.6",
            "obs": "18",
            "arc": "0.59",
            "status": "pending"
        },
        {
            "id": "C1GV6U5",
            "designation": "C1GV6U5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "097",
            "mag": "28.3",
            "obs": "11",
            "arc": "0.79",
            "status": "pending"
        },
        {
            "id": "C1GUXM5",
            "designation": "C1GUXM5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "098",
            "mag": "27.8",
            "obs": "10",
            "arc": "0.81",
            "status": "pending"
        },
        {
            "id": "CEWAAC2",
            "designation": "CEWAAC2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "098",
            "mag": "28.6",
            "obs": "12",
            "arc": "0.89",
            "status": "pending"
        },
        {
            "id": "CEW76J2",
            "designation": "CEW76J2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "092",
            "mag": "28.2",
            "obs": "10",
            "arc": "0.93",
            "status": "pending"
        },
        {
            "id": "C1GTXK5",
            "designation": "C1GTXK5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "085",
            "mag": "27.1",
            "obs": "8",
            "arc": "0.07",
            "status": "pending"
        },
        {
            "id": "CEW8VV2",
            "designation": "CEW8VV2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "095",
            "mag": "28.9",
            "obs": "13",
            "arc": "0.93",
            "status": "pending"
        },
        {
            "id": "C1GTPE5",
            "designation": "C1GTPE5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "098",
            "mag": "27.8",
            "obs": "10",
            "arc": "0.80",
            "status": "pending"
        },
        {
            "id": "C1GTPF5",
            "designation": "C1GTPF5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "27.0",
            "obs": "7",
            "arc": "0.06",
            "status": "pending"
        },
        {
            "id": "CEW8F82",
            "designation": "CEW8F82",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "086",
            "mag": "28.6",
            "obs": "16",
            "arc": "2.05",
            "status": "pending"
        },
        {
            "id": "C1GR325",
            "designation": "C1GR325",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "089",
            "mag": "27.6",
            "obs": "6",
            "arc": "0.06",
            "status": "pending"
        },
        {
            "id": "C1GR0W5",
            "designation": "C1GR0W5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "097",
            "mag": "28.5",
            "obs": "13",
            "arc": "0.91",
            "status": "pending"
        },
        {
            "id": "CEW2VG2",
            "designation": "CEW2VG2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "088",
            "mag": "28.8",
            "obs": "19",
            "arc": "0.92",
            "status": "pending"
        },
        {
            "id": "6K72D21",
            "designation": "6K72D21",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "086",
            "mag": "29.0",
            "obs": "17",
            "arc": "1.00",
            "status": "pending"
        },
        {
            "id": "C1GQWZ5",
            "designation": "C1GQWZ5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "044",
            "mag": "28.0",
            "obs": "9",
            "arc": "0.83",
            "status": "pending"
        },
        {
            "id": "CEVYPP2",
            "designation": "CEVYPP2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "093",
            "mag": "28.0",
            "obs": "21",
            "arc": "0.90",
            "status": "pending"
        },
        {
            "id": "C1GQQN5",
            "designation": "C1GQQN5",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "28.1",
            "obs": "13",
            "arc": "4.97",
            "status": "pending"
        },
        {
            "id": "C46NDW1",
            "designation": "C46NDW1",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "098",
            "mag": "30.1",
            "obs": "10",
            "arc": "0.23",
            "status": "pending"
        },
        {
            "id": "orA5873",
            "designation": "orA5873",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "100",
            "mag": "29.8",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "CANPMAZ",
            "designation": "CANPMAZ",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "27.6",
            "obs": "4",
            "arc": "0.02",
            "status": "pending"
        },
        {
            "id": "CEVT4K2",
            "designation": "CEVT4K2",
            "name": "",
            "first_seen": "2026-10-08",
            "observer": "054",
            "mag": "28.7",
            "obs": "10",
            "arc": "0.93",
            "status": "pending"
        },
        {
            "id": "N033125",
            "designation": "N033125",
            "name": "",
            "first_seen": "2026-10-04",
            "observer": "097",
            "mag": "28.5",
            "obs": "4",
            "arc": "0.08",
            "status": "pending"
        },
        {
            "id": "N117108",
            "designation": "N117108",
            "name": "",
            "first_seen": "2026-10-02",
            "observer": "100",
            "mag": "",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "N015193",
            "designation": "N015193",
            "name": "",
            "first_seen": "2026-10-01",
            "observer": "100",
            "mag": "28.7",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "N015143",
            "designation": "N015143",
            "name": "",
            "first_seen": "2026-10-05",
            "observer": "100",
            "mag": "25.2",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "N051198",
            "designation": "N051198",
            "name": "",
            "first_seen": "2026-10-05",
            "observer": "085",
            "mag": "28.9",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "N125213",
            "designation": "N125213",
            "name": "",
            "first_seen": "2026-10-05",
            "observer": "092",
            "mag": "",
            "obs": "4",
            "arc": "0.08",
            "status": "pending"
        },
        {
            "id": "N070166",
            "designation": "N070166",
            "name": "",
            "first_seen": "2026-10-05",
            "observer": "100",
            "mag": "28.3",
            "obs": "4",
            "arc": "0.11",
            "status": "pending"
        },
        {
            "id": "ZTF10Gf",
            "designation": "ZTF10Gf",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "098",
            "mag": "27.3",
            "obs": "8",
            "arc": "1.09",
            "status": "pending"
        },
        {
            "id": "CEVRWL2",
            "designation": "CEVRWL2",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "28.3",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "CEVQWE2",
            "designation": "CEVQWE2",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "29.0",
            "obs": "3",
            "arc": "0.01",
            "status": "pending"
        },
        {
            "id": "CEVRR22",
            "designation": "CEVRR22",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "095",
            "mag": "29.7",
            "obs": "9",
            "arc": "0.92",
            "status": "pending"
        },
        {
            "id": "C1GN5U5",
            "designation": "C1GN5U5",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "098",
            "mag": "27.7",
            "obs": "11",
            "arc": "0.86",
            "status": "pending"
        },
        {
            "id": "C1GM215",
            "designation": "C1GM215",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "27.9",
            "obs": "15",
            "arc": "1.04",
            "status": "pending"
        },
        {
            "id": "C1GLQL5",
            "designation": "C1GLQL5",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "100",
            "mag": "27.7",
            "obs": "10",
            "arc": "0.80",
            "status": "pending"
        },
        {
            "id": "C1GLFL5",
            "designation": "C1GLFL5",
            "name": "",
            "first_seen": "2026-10-07",
            "observer": "073",
            "mag": "28.5",
            "obs": "10",
            "arc": "0.81",
            "status": "pending"
        }
    ],
    "tracker": {
        "totalCandidates": 127,
        "statusCounts": {
            "pending": 127
        },
        "topCandidates": [
            {
                "designation": "C46NXG1",
                "status": "pending"
            },
            {
                "designation": "C46NWU1",
                "status": "pending"
            },
            {
                "designation": "C46NVG1",
                "status": "pending"
            },
            {
                "designation": "CEWL7R2",
                "status": "pending"
            },
            {
                "designation": "CEWH582",
                "status": "pending"
            },
            {
                "designation": "CEWGUW2",
                "status": "pending"
            },
            {
                "designation": "CEWGHC2",
                "status": "pending"
            },
            {
                "designation": "CARD7TZ",
                "status": "pending"
            },
            {
                "designation": "CARD7VZ",
                "status": "pending"
            },
            {
                "designation": "XL1008A",
                "status": "pending"
            }
        ]
    },
    "stats": {
        "earlyDiscoveries": 78,
        "highConfidenceCandidates": 78,
        "avgLeadTimeDays": 0.0,
        "discoveryByYear": {
            "labels": [
                "2017",
                "2018",
                "2019",
                "2020",
                "2021",
                "2022",
                "2023",
                "2024",
                "2025",
                "2026"
            ],
            "data": [
                2002,
                1741,
                2305,
                2708,
                2877,
                2999,
                2784,
                3005,
                3157,
                2038
            ]
        }
    },
    "earlyDiscoveries": []
};
}
