/**
 * NEO Discovery Dashboard — Auto-generated Data
 * Last updated: 2026-06-23T06:48:40.772426
 * 
 * Sources: NASA NEOWS, MPC NEO Confirmation Page, NASA SBDB
 * DO NOT EDIT — regenerated by update_dashboard.py
 */

function generateDashboardData() {
    return {
    "meta": {
        "lastUpdate": "2026-06-23T06:48:40.772426",
        "sources": [
            "NASA NEOWS",
            "MPC NEO Confirmation Page",
            "NASA SBDB"
        ],
        "version": "1.0"
    },
    "catalog": {
        "totalNEOs": 61859,
        "phaCount": 3856,
        "newThisYear": 222,
        "newThisMonth": 222,
        "orbitClasses": {
            "Apollo": 34895,
            "Amor": 21939,
            "Aten": 4969,
            "IEO": 52,
            "Other": 4
        }
    },
    "approaches": [
        {
            "name": "(2012 GV11)",
            "desig": "3602572",
            "date": "2026-06-23",
            "distLD": 144.3983385339,
            "vel": 17.1041549895,
            "dia_min": 100.5900390178,
            "dia_max": 224.9261651032,
            "pha": false
        },
        {
            "name": "(2012 KC45)",
            "desig": "3605306",
            "date": "2026-06-23",
            "distLD": 139.509506696,
            "vel": 15.1167257308,
            "dia_min": 3.5039264111,
            "dia_max": 7.8350176433,
            "pha": false
        },
        {
            "name": "(2014 DH)",
            "desig": "3662200",
            "date": "2026-06-23",
            "distLD": 64.8380799243,
            "vel": 15.7158211069,
            "dia_min": 12.7219878539,
            "dia_max": 28.4472296503,
            "pha": false
        },
        {
            "name": "(2016 VX1)",
            "desig": "3763337",
            "date": "2026-06-23",
            "distLD": 161.3706898198,
            "vel": 9.199374076,
            "dia_min": 26.58,
            "dia_max": 59.4346868419,
            "pha": false
        },
        {
            "name": "(2017 BB7)",
            "desig": "3767014",
            "date": "2026-06-23",
            "distLD": 104.6847002211,
            "vel": 8.5826563798,
            "dia_min": 6.3760978988,
            "dia_max": 14.2573883328,
            "pha": false
        },
        {
            "name": "(2020 AT)",
            "desig": "3972419",
            "date": "2026-06-23",
            "distLD": 60.9855117216,
            "vel": 9.9891657523,
            "dia_min": 24.2412481101,
            "dia_max": 54.2050786336,
            "pha": false
        },
        {
            "name": "(2015 NG13)",
            "desig": "3724056",
            "date": "2026-06-24",
            "distLD": 165.7578424784,
            "vel": 17.8295351471,
            "dia_min": 27.8326768072,
            "dia_max": 62.2357573367,
            "pha": false
        },
        {
            "name": "(2010 WU8)",
            "desig": "3552654",
            "date": "2026-06-25",
            "distLD": 84.1596098346,
            "vel": 6.7656654127,
            "dia_min": 38.4197891064,
            "dia_max": 85.9092601232,
            "pha": false
        },
        {
            "name": "(2013 KF6)",
            "desig": "3639420",
            "date": "2026-06-25",
            "distLD": 168.5704091449,
            "vel": 15.8250116675,
            "dia_min": 146.0679642714,
            "dia_max": 326.6178974458,
            "pha": false
        },
        {
            "name": "(2016 LS68)",
            "desig": "3838921",
            "date": "2026-06-25",
            "distLD": 192.195607568,
            "vel": 2.8959893761,
            "dia_min": 96.5061469579,
            "dia_max": 215.7943048444,
            "pha": false
        },
        {
            "name": "(2016 VK)",
            "desig": "3763232",
            "date": "2026-06-25",
            "distLD": 58.9344383069,
            "vel": 22.2762128076,
            "dia_min": 84.0533402073,
            "dia_max": 187.9489824394,
            "pha": false
        },
        {
            "name": "(2018 CP2)",
            "desig": "3799283",
            "date": "2026-06-25",
            "distLD": 56.0335877014,
            "vel": 14.4699117772,
            "dia_min": 36.6906137531,
            "dia_max": 82.0427064882,
            "pha": false
        },
        {
            "name": "(2018 GE2)",
            "desig": "3802442",
            "date": "2026-06-25",
            "distLD": 114.9721972164,
            "vel": 6.1970378622,
            "dia_min": 10.3885510102,
            "dia_max": 23.2295062464,
            "pha": false
        },
        {
            "name": "(2018 MJ7)",
            "desig": "3825491",
            "date": "2026-06-25",
            "distLD": 53.6185563173,
            "vel": 16.0624245764,
            "dia_min": 62.0233152954,
            "dia_max": 138.6883491905,
            "pha": false
        },
        {
            "name": "(2022 CL12)",
            "desig": "54250323",
            "date": "2026-06-25",
            "distLD": 188.761344797,
            "vel": 5.0104850007,
            "dia_min": 65.8498782919,
            "dia_max": 147.2448041708,
            "pha": false
        },
        {
            "name": "499998 (2011 PT)",
            "desig": "2499998",
            "date": "2026-06-26",
            "distLD": 132.8397478227,
            "vel": 4.2163798544,
            "dia_min": 41.9329075486,
            "dia_max": 93.7648317729,
            "pha": false
        },
        {
            "name": "(2002 EM7)",
            "desig": "3117427",
            "date": "2026-06-26",
            "distLD": 44.0025996692,
            "vel": 7.5060625901,
            "dia_min": 35.0392641108,
            "dia_max": 78.3501764334,
            "pha": false
        },
        {
            "name": "(2014 MR67)",
            "desig": "3674825",
            "date": "2026-06-26",
            "distLD": 95.9952740426,
            "vel": 17.0666004135,
            "dia_min": 73.2073989347,
            "dia_max": 163.696720474,
            "pha": false
        },
        {
            "name": "(2014 NV63)",
            "desig": "3674745",
            "date": "2026-06-26",
            "distLD": 21.7629322268,
            "vel": 14.3340059329,
            "dia_min": 60.0558027725,
            "dia_max": 134.2888574426,
            "pha": false
        },
        {
            "name": "(2016 JH17)",
            "desig": "3753023",
            "date": "2026-06-26",
            "distLD": 180.1001557006,
            "vel": 20.3584848737,
            "dia_min": 229.3796979965,
            "dia_max": 512.9085973785,
            "pha": false
        },
        {
            "name": "(2016 TA57)",
            "desig": "3761034",
            "date": "2026-06-26",
            "distLD": 181.8712477657,
            "vel": 23.504812676,
            "dia_min": 184.7374636151,
            "dia_max": 413.0855266343,
            "pha": true
        },
        {
            "name": "(2018 LW5)",
            "desig": "3825247",
            "date": "2026-06-26",
            "distLD": 90.4469875818,
            "vel": 11.8713770596,
            "dia_min": 196.1349443683,
            "dia_max": 438.5710683707,
            "pha": false
        },
        {
            "name": "(2018 NV)",
            "desig": "3825562",
            "date": "2026-06-26",
            "distLD": 39.2604689506,
            "vel": 6.1759420576,
            "dia_min": 72.536229467,
            "dia_max": 162.1959399198,
            "pha": false
        },
        {
            "name": "152637 (1997 NC1)",
            "desig": "2152637",
            "date": "2026-06-27",
            "distLD": 6.6719676542,
            "vel": 8.8866889897,
            "dia_min": 708.8510330298,
            "dia_max": 1585.0390957756,
            "pha": true
        },
        {
            "name": "276891 (2004 RH340)",
            "desig": "2276891",
            "date": "2026-06-27",
            "distLD": 174.7560281098,
            "vel": 13.0323031194,
            "dia_min": 330.0311833581,
            "dia_max": 737.9721606833,
            "pha": false
        },
        {
            "name": "(2005 TE49)",
            "desig": "3293831",
            "date": "2026-06-27",
            "distLD": 165.8529306887,
            "vel": 23.2325025896,
            "dia_min": 14.0137697166,
            "dia_max": 31.3357417074,
            "pha": false
        },
        {
            "name": "(2016 XR23)",
            "desig": "3766036",
            "date": "2026-06-27",
            "distLD": 36.0055509341,
            "vel": 4.3444451811,
            "dia_min": 22.1082810359,
            "dia_max": 49.435619262,
            "pha": false
        },
        {
            "name": "(2018 VP5)",
            "desig": "3836124",
            "date": "2026-06-27",
            "distLD": 190.9677778486,
            "vel": 19.608795676,
            "dia_min": 23.150212221,
            "dia_max": 51.7654482198,
            "pha": false
        },
        {
            "name": "(2019 NG)",
            "desig": "3843085",
            "date": "2026-06-27",
            "distLD": 35.4766913134,
            "vel": 6.0136534197,
            "dia_min": 36.6906137531,
            "dia_max": 82.0427064882,
            "pha": false
        },
        {
            "name": "(2015 MO66)",
            "desig": "3722209",
            "date": "2026-06-28",
            "distLD": 93.8124153246,
            "vel": 21.120499169,
            "dia_min": 253.8370293645,
            "dia_max": 567.5968528656,
            "pha": false
        },
        {
            "name": "(2015 VH66)",
            "desig": "3734186",
            "date": "2026-06-28",
            "distLD": 61.0134132523,
            "vel": 25.6275645752,
            "dia_min": 262.1530872808,
            "dia_max": 586.1921236712,
            "pha": false
        },
        {
            "name": "(2015 YC1)",
            "desig": "3738913",
            "date": "2026-06-29",
            "distLD": 100.4393019633,
            "vel": 15.3830860117,
            "dia_min": 16.7708462163,
            "dia_max": 37.5007521798,
            "pha": false
        },
        {
            "name": "(2019 YO4)",
            "desig": "3959234",
            "date": "2026-06-29",
            "distLD": 93.4717955658,
            "vel": 21.8146131803,
            "dia_min": 111.3153296083,
            "dia_max": 248.908643942,
            "pha": false
        },
        {
            "name": "398188 Agni (2010 LE15)",
            "desig": "2398188",
            "date": "2026-06-30",
            "distLD": 74.3994080576,
            "vel": 7.7867991752,
            "dia_min": 361.8719965994,
            "dia_max": 809.1703835499,
            "pha": true
        },
        {
            "name": "(2016 AR130)",
            "desig": "3739621",
            "date": "2026-06-30",
            "distLD": 140.7221011915,
            "vel": 36.0775469848,
            "dia_min": 217.0475943071,
            "dia_max": 485.3331752235,
            "pha": false
        },
        {
            "name": "(2018 ES3)",
            "desig": "3799876",
            "date": "2026-06-30",
            "distLD": 130.0008958038,
            "vel": 8.8366768242,
            "dia_min": 31.3729224956,
            "dia_max": 70.151987353,
            "pha": false
        },
        {
            "name": "(2020 BW12)",
            "desig": "3989284",
            "date": "2026-06-30",
            "distLD": 153.3372065667,
            "vel": 15.8290761044,
            "dia_min": 16.0160337979,
            "dia_max": 35.8129403019,
            "pha": false
        }
    ],
    "candidates": [
        {
            "id": "CEQ9YD2",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 3.0,
            "observer": "MPC 100",
            "confidence": 30,
            "status": "pending"
        },
        {
            "id": "A11DV3J",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 9.0,
            "observer": "MPC 100",
            "confidence": 90,
            "status": "pending"
        },
        {
            "id": "P12nL5l",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 3.0,
            "observer": "MPC 100",
            "confidence": 30,
            "status": "pending"
        },
        {
            "id": "P22nL5u",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 3.0,
            "observer": "MPC 90",
            "confidence": 30,
            "status": "pending"
        },
        {
            "id": "P22nL5t",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 4.0,
            "observer": "MPC 96",
            "confidence": 40,
            "status": "pending"
        },
        {
            "id": "P22nJzK",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 5.0,
            "observer": "MPC 96",
            "confidence": 50,
            "status": "pending"
        },
        {
            "id": "P22nJzF",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 12.0,
            "observer": "MPC 100",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P22nJzJ",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 5.0,
            "observer": "MPC 100",
            "confidence": 50,
            "status": "pending"
        },
        {
            "id": "P12nJzz",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 7.0,
            "observer": "MPC 76",
            "confidence": 70,
            "status": "pending"
        },
        {
            "id": "P22nJxG",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 10.0,
            "observer": "MPC 98",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P22nJxH",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 6.0,
            "observer": "MPC 100",
            "confidence": 60,
            "status": "pending"
        },
        {
            "id": "P22nJxs",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 6.0,
            "observer": "MPC 80",
            "confidence": 60,
            "status": "pending"
        },
        {
            "id": "C1FK5V5",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 7.0,
            "observer": "MPC 100",
            "confidence": 70,
            "status": "pending"
        },
        {
            "id": "C1FK4P5",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 8.0,
            "observer": "MPC 77",
            "confidence": 80,
            "status": "pending"
        },
        {
            "id": "P12nJxm",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 26.0,
            "observer": "MPC 77",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "CEQ6EW2",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 6.0,
            "observer": "MPC 100",
            "confidence": 60,
            "status": "pending"
        },
        {
            "id": "A11DPEP",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 3.0,
            "observer": "MPC 100",
            "confidence": 30,
            "status": "pending"
        },
        {
            "id": "C1FJJ35",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 10.0,
            "observer": "MPC 98",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "C1FJ965",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 14.0,
            "observer": "MPC 100",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "C1FHUX5",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 12.0,
            "observer": "MPC 98",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "C1FHJC5",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 7.0,
            "observer": "MPC 100",
            "confidence": 70,
            "status": "pending"
        },
        {
            "id": "P22nG1B",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 8.0,
            "observer": "MPC 71",
            "confidence": 80,
            "status": "pending"
        },
        {
            "id": "P22nFZm",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 12.0,
            "observer": "MPC 99",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12nFZe",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 9.0,
            "observer": "MPC 66",
            "confidence": 90,
            "status": "pending"
        },
        {
            "id": "C1FG7D5",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 11.0,
            "observer": "MPC 100",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "C1FFC85",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 14.0,
            "observer": "MPC 96",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12nFWf",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 12.0,
            "observer": "MPC 94",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "C1FEVW5",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 18.0,
            "observer": "MPC 91",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "C1FDRW5",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 8.0,
            "observer": "MPC 100",
            "confidence": 80,
            "status": "pending"
        },
        {
            "id": "P22nCie",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 10.0,
            "observer": "MPC 64",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P22nChu",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 27.0,
            "observer": "MPC 72",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P22nCgP",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 19.0,
            "observer": "MPC 74",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12nCgf",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 12.0,
            "observer": "MPC 61",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12nCdO",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 5.0,
            "observer": "MPC 100",
            "confidence": 50,
            "status": "pending"
        },
        {
            "id": "CEPLLF2",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 26.0,
            "observer": "MPC 41",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12nCaK",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 9.0,
            "observer": "MPC 97",
            "confidence": 90,
            "status": "pending"
        },
        {
            "id": "P22nCaF",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 21.0,
            "observer": "MPC 80",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "8N62001",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 3.0,
            "observer": "MPC 100",
            "confidence": 30,
            "status": "pending"
        },
        {
            "id": "P12nBR5",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 6.0,
            "observer": "MPC 75",
            "confidence": 60,
            "status": "pending"
        },
        {
            "id": "P12nBR1",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 17.0,
            "observer": "MPC 87",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12nBR7",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 14.0,
            "observer": "MPC 45",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12ny2Q",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 11.0,
            "observer": "MPC 45",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12ny2P",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 15.0,
            "observer": "MPC 52",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12ny2h",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 23.0,
            "observer": "MPC 100",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12ny2g",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 4.0,
            "observer": "MPC 68",
            "confidence": 40,
            "status": "pending"
        },
        {
            "id": "P22nxWm",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 3.0,
            "observer": "MPC 100",
            "confidence": 30,
            "status": "pending"
        },
        {
            "id": "P12nxU3",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 15.0,
            "observer": "MPC 91",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "orA4457",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 3.0,
            "observer": "MPC 100",
            "confidence": 30,
            "status": "pending"
        },
        {
            "id": "CEPC7K2",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 23.0,
            "observer": "MPC 77",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "ST26F62",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 12.0,
            "observer": "MPC 98",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "XA9xaXA",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 10.0,
            "observer": "MPC 100",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "A11DIrs",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 4.0,
            "observer": "MPC 100",
            "confidence": 40,
            "status": "pending"
        },
        {
            "id": "P12nuG0",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 14.0,
            "observer": "MPC 27",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "P12nuFZ",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 14.0,
            "observer": "MPC 47",
            "confidence": 95,
            "status": "pending"
        },
        {
            "id": "CEP9TG2",
            "arc": 0.0,
            "obs": 0,
            "mag": 99,
            "scale": 3.0,
            "observer": "MPC 100",
            "confidence": 30,
            "status": "pending"
        }
    ],
    "stats": {
        "earlyDiscoveries": 0,
        "highConfidenceCandidates": 0,
        "avgLeadTimeDays": 0,
        "discoveryByYear": {
            "labels": [
                "2019",
                "2020",
                "2021",
                "2022",
                "2023",
                "2024",
                "2025",
                "2026"
            ],
            "data": [
                8500,
                12000,
                9800,
                10500,
                11200,
                12800,
                15157,
                222
            ]
        }
    },
    "earlyDiscoveries": []
};
}

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { generateDashboardData };
}
